apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikimedia-deployment
  labels:
    app: wikimedia
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wikimedia
        type: web
    spec:
      containers:
        - name: wikimedia
          image: mrabinesh/wiki:1
          ports:
            - containerPort: 80
              name: httpd-port
          env:
            - name: WIKIMEDIA_DB_HOST
              value: mariadb-service
            - name: WIKIMEDIA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: WIKIMEDIA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword
            - name: WIKIMEDIA_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname      
